#!/bin/bash
# =============================================================================
# Dev-only sweep of the LM-fusion weights (lm_weight lambda x ilm_weight alpha)
# for the AED +LM beam cell, both grid cells, four workers on four GPUs.
#
# Picks the weights for the aed_beam_lm / joint_beam_lm cells BEFORE the real
# decode. Runs on a RANDOM dev-clean subset: the previous value was chosen on
# the six longest utterances, which overstates truncation and shipped a bonus
# that over-generated by 15% on typical audio.
#
# The measured length-neutral ray is alpha ~ 0.67*lambda (H_ext 2.38 nats,
# H_ILM 3.55 nats), so the grid brackets that ray rather than searching blind.
# =============================================================================

#SBATCH --job-name=dcasr_lm_sweep
#SBATCH --output=/data/user_data/anshulk/hnet-asr/logs/slurm-sweep-%j.out
#SBATCH --error=/data/user_data/anshulk/hnet-asr/logs/slurm-sweep-%j.err
#SBATCH --open-mode=append
#SBATCH --partition=general
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=4:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=anshulk@andrew.cmu.edu

set -uo pipefail
echo "[$(date)] host=$(hostname) job=${SLURM_JOB_ID:-?}"
source /home/anshulk/miniconda3/etc/profile.d/conda.sh
conda activate hnet-asr
cd /home/anshulk/H-Net_Mamba_ASR
ENVBIN=/data/user_data/anshulk/envs/hnet-asr/bin
export PYTHONDONTWRITEBYTECODE=1

N=${SWEEP_N:-250}
SEED=1234
run() {   # <gpu> <run_name> <tag> <lm_weights> <ilm_weights>
  CUDA_VISIBLE_DEVICES=$1 $ENVBIN/python scripts/analysis/sweep_lm_fusion.py \
    --config configs/$2.yaml --checkpoint checkpoints/$2/valid.wer.ave.pt \
    --n "$N" --seed "$SEED" --tag "$3" --lm-weights "$4" --ilm-weights "$5" \
    > "logs/sweep_$2_$3.txt" 2>&1
}

# SMALL lambda. The AED's own per-token entropy is only 0.144 nats (87% mean probability
# on the correct token), so lambda=0.3 injected 0.71 nats/token of LM opinion — five times
# the entire signal it was advising, which is why no alpha stabilized it. Matching the LM
# term to the acoustic model's uncertainty gives lambda ~ 0.144/2.381 ~ 0.06. alpha=0 is
# swept alongside the length-neutral alpha=0.67*lambda: at small lambda the accumulated
# per-token drag stays under the AED's 8.6-nat eos discrimination, so plain shallow fusion
# may need no correction at all.
run 0 typeA_small_N1 a 0.05,0.1  0.0,0.034,0.067 &
run 1 typeA_small_N1 b 0.15,0.2  0.0,0.10,0.134  &
run 2 typeA_small_N2 a 0.05,0.1  0.0,0.034,0.067 &
run 3 typeA_small_N2 b 0.15,0.2  0.0,0.10,0.134  &
wait

echo "[$(date)] SWEEP COMPLETE"
for f in logs/sweep_typeA_small_N*_*.txt; do echo "── $f"; cat "$f"; done
